[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitive Ethereum abstractions for Substrate."
documentation = "https://docs.rs/fp-ethereum"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "fp-self-contained"
repository = "https://github.com/paritytech/frontier/"
version = "1.0.0-dev"

[dependencies]
ethereum = {version = "0.11.1", default-features = false, features = ["with-codec"]}
serde = {version = "1.0.101", features = ["derive"], optional = true}

codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false}
frame-support = {version = "4.0.0-dev", git = "https://github.com/ultrastable-money/substrate", branch = "hydro-dep-polkadot-v0.9.16", default-features = false}
parity-util-mem = {version = "0.10", optional = true}
scale-info = {version = "1.0.0", default-features = false, features = ["derive"]}
sp-debug-derive = {version = "4.0.0", git = "https://github.com/ultrastable-money/substrate", branch = "hydro-dep-polkadot-v0.9.16", default-features = false}
sp-io = {version = "4.0.0", git = "https://github.com/ultrastable-money/substrate", branch = "hydro-dep-polkadot-v0.9.16", default-features = false}
sp-runtime = {version = "4.1.0-dev", git = "https://github.com/ultrastable-money/substrate", branch = "hydro-dep-polkadot-v0.9.16", default-features = false}

[features]
default = ["std"]
std = [
  "ethereum/std",
  "serde",
  "codec/std",
  "scale-info/std",
  "parity-util-mem",
  "sp-debug-derive/std",
  "sp-runtime/std",
  "frame-support/std",
]
