[package]
authors = ["Parity Technologies <admin@parity.io"]
description = "Runtime primitives for Ethereum RPC (web3) compatibility layer for Substrate."
edition = "2021"
license = "Apache-2.0"
name = "fp-rpc"
version = "3.0.0-dev"

[dependencies]
ethereum = {version = "0.11.1", default-features = false, features = ["with-codec"]}
ethereum-types = {version = "0.12", default-features = false}

codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false}
scale-info = {version = "1.0.0", default-features = false, features = ["derive"]}
sp-api = {version = "4.0.0-dev", git = "https://github.com/ultrastable-money/substrate", branch = "hydro-dep-polkadot-v0.9.16", default-features = false}
sp-core = {version = "4.1.0-dev", git = "https://github.com/ultrastable-money/substrate", branch = "hydro-dep-polkadot-v0.9.16", default-features = false}
sp-io = {version = "4.0.0", git = "https://github.com/ultrastable-money/substrate", branch = "hydro-dep-polkadot-v0.9.16", default-features = false}
sp-runtime = {version = "4.1.0-dev", git = "https://github.com/ultrastable-money/substrate", branch = "hydro-dep-polkadot-v0.9.16", default-features = false}
sp-std = {version = "4.0.0", git = "https://github.com/ultrastable-money/substrate", branch = "hydro-dep-polkadot-v0.9.16", default-features = false}

fp-evm = {version = "3.0.0-dev", default-features = false, path = "../../primitives/evm"}

[features]
default = ["std"]
std = [
  "ethereum/std",
  "ethereum-types/std",
  "codec/std",
  "scale-info/std",
  "sp-api/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
  "fp-evm/std",
]
